# $schema: ../../assets/docs/schemas/config.schema.json
# yaml-language-server: $schema=../../assets/docs/schemas/config.schema.json

# This file has a schema, ypu can read it to get additional definations
# Suggest use: yaml-language-server in vscode to see comments and auto-complitions

util:
    general_ver_mapper: &general_ver_mapper
    # this version mapper cam map any version like (v?)a.b(.c)?(-*)*(-sp*)*(-*)
        version_mapper:
            type: lambda
            mapper: |
                lambda ver, info: [
                    (
                        m := re.match(r"(v)?0*(?P<major>\d+)(\.0*(?P<minor>\d+))?(\.0*(?P<patch>\d+))?(?P<pre_release_1>(-(?:(?!(SP|trunk\.|LTS))[\w\.]+))*)(-LTS)?(-(SP|trunk\.)(?P<sp_part>\d+))?(-LTS)?(?P<pre_release_2>(-([\w\.]+))*)?(?P<build>(\+([\w\.]+))*)?", ver),
                        f"0.{m["major"]}.0" if not m["minor"] else 
                            f"{m["major"]}{int(m["minor"]):02d}.{m["patch"] or 0}.{m["sp_part"] or 0}{f"{m["pre_release_1"] or ""}{m["pre_release_2"] or ""}".replace('-', '.').replace('.', '-', 1)}{m["build"] or ""}"
                    )[-1] 
                    for re in [__import__("re")]
                ][0]

handler:
    -   plugin: mirrorsite_getter_std
        vendor: sipeed-lpi4a
        system: openeuler
        variant: LTS
        board_variants: [ 16g ]
        <<: 
            - *general_ver_mapper
        strategy: fastboot-v1
        fileset:
            -   id: 'main'
                board_variants: null
                desc_mapper:
                    mapper: 'openEuler {info.version} image for Sipeed LicheePi 4A'
            -   id: 'uboot-16g'
                prepend: 'uboot'
                board_variants: [ 16g ]
                desc_mapper:
                    mapper: 'U-Boot image for LicheePi 4A (16G RAM) and openEuler {info.version}'
        files:
            -   id: "boot file"
                fileset: [ main ]
                file_filter:
                    type: lambda
                    filter: 'lambda name, info: "boot" in name and "u-boot" not in name and "sha" not in name'
                partition_map: "boot"
            -   id: "root file"
                fileset: [ main ]
                file_filter:
                    type: lambda
                    filter: 'lambda name, info: "root" in name and "sha" not in name'
                partition_map: "root"
            -   id: "uboot 16g file"
                fileset: [ uboot-16g ]
                file_filter:
                    type: lambda
                    filter: 'lambda name, info: "u-boot" in name and "16g" in name and "sha" not in name'
                partition_map: "uboot"
        url:
            regex: (.*)
            mapper: 'https://fast-mirror.isrc.ac.cn/openeuler/openEuler-{0}/embedded_img/riscv64/lpi4a/'
    -   plugin: mirrorsite_getter_std
        vendor: sipeed-lpi4a
        system: openeuler
        variant: Innovation
        board_variants: [ 16g ]
        <<: 
            - *general_ver_mapper
        strategy: fastboot-v1
        fileset:
            -   id: 'main'
                board_variants: null
                desc_mapper:
                    mapper: 'openEuler {info.version} image for Sipeed LicheePi 4A'
            -   id: 'uboot-16g'
                prepend: 'uboot'
                board_variants: [ 16g ]
                desc_mapper:
                    mapper: 'U-Boot image for LicheePi 4A (16G RAM) and openEuler {info.version}'
        files:
            -   id: "boot file"
                fileset: [ main ]
                file_filter:
                    type: lambda
                    filter: 'lambda name, info: "boot" in name and "u-boot" not in name and "sha" not in name'
                partition_map: "boot"
            -   id: "root file"
                fileset: [ main ]
                file_filter:
                    type: lambda
                    filter: 'lambda name, info: "root" in name and "sha" not in name'
                partition_map: "root"
            -   id: "uboot 16g file"
                fileset: [ uboot-16g ]
                file_filter:
                    type: lambda
                    filter: 'lambda name, info: "u-boot" in name and "16g" in name and "sha" not in name'
                partition_map: "uboot"
        url:
            regex: (.*)
            mapper: 'https://fast-mirror.isrc.ac.cn/openeuler/openEuler-{0}/embedded_img/riscv64/lpi4a/'