# $schema: ../../assets/docs/schemas/config.schema.json
# yaml-language-server: $schema=../../assets/docs/schemas/config.schema.json

# This file has a schema, ypu can read it to get additional definations
# Suggest use: yaml-language-server in vscode to see comments and auto-complitions

util:
    general_ver_mapper: &general_ver_mapper
    # this version mapper cam map any version like (v?)a.b(.c)?(-*)*(-sp*)*(-*)
        version_mapper:
            type: lambda
            mapper: 'lambda ver, info: [(m := re.match(r"(v)?0*(\d+)\.0*(\d+)(\.0*(\d+))?((-(?:(?!SP)[\w\.]+))*)(-SP(\d+))?((-([\w\.]+))*)?((\+([\w\.]+))*)?", ver), f"{m[2]}.{m[3]}.{m[5] or 0}-{m[9] or 0}{m[6] or ""}{m[10] or ""}{m[13] or ""}")[-1] for re in [__import__("re")]][0]'
    filter_version_in_release: &release_in_filter
        release_filter:
            type: lambda
            filter: "lambda name, info: info.version in name"

handler:
    -   plugin: github_release_simple
        vendor: pine64-star64
        system: armbian
        variant: null
        repo: armbian/community
        <<: 
            - *release_in_filter
            - *general_ver_mapper
        asset_filter:
            type: lambda
            filter: 'lambda name, info: "Star64" in name and "img" in name and "txt" not in name and "sha" not in name and "asc" not in name and "torrent" not in name'
