# $schema: ../../assets/docs/schemas/config.schema.json
# yaml-language-server: $schema=../../assets/docs/schemas/config.schema.json

# This file has a schema, ypu can read it to get additional definations
# Suggest use: yaml-language-server in vscode to see comments and auto-complitions

# You shall rename this file to config.yml

util:
    general_ver_mapper: &general_ver_mapper
    # this version mapper cam map any version like (v?)a.b(.c)?(-*)*(-sp*)*(-*)
        version_mapper:
            type: lambda
            mapper: 'lambda ver, info: [(m := re.match(r"(v)?0*(\d+)\.0*(\d+)(\.0*(\d+))?((-(?:(?!SP)[\w\.]+))*)(-SP(\d+))?((-([\w\.]+))*)?((\+([\w\.]+))*)?", ver), f"{m[2]}.{m[3]}.{m[5] or 0}-{m[9] or 0}{m[6] or ""}{m[10] or ""}{m[13] or ""}")[-1] for re in [__import__("re")]][0]'

handler:
    -   plugin: mirrorsite_getter_simple
        vendor: sifive-unmatched
        system: openwrt
        variant: null
        url:
            regex: v?(.*)
            mapper: https://downloads.openwrt.org/releases/{0}/targets/sifiveu/generic/
        file_filter:
            type: lambda
            filter: 'lambda name, info: "unmatched" in name and "img" in name'
        <<: *general_ver_mapper
        desc_mapper:
            mapper: Official OpenWRT {info.version} image for SiFive Unmatched