# $schema: ../../assets/docs/schemas/config.schema.json
# yaml-language-server: $schema=../../assets/docs/schemas/config.schema.json

# This file has a schema, ypu can read it to get additional definations
# Suggest use: yaml-language-server in vscode to see comments and auto-complitions

util:
    date_middle_mapper: &date_middle_mapper
        version_mapper:
            regex: '(.*)'
            mapper: '0.{0}.0'
    filter_version_in_release: &release_in_filter
        release_filter:
            type: lambda
            filter: "lambda name, info: info.version in name"

handler:
    -   plugin: github_release_simple
        id: buildroot-sipeed-licheervnano
        vendor: sipeed-licheervnano
        system: buildroot
        variant: null
        repo: sipeed/LicheeRV-Nano-Build
        strategy: dd_v1
        partition_map: disk
        <<: 
            - *date_middle_mapper
            - *release_in_filter
        asset_filter:
            filter: .*\.img