# $schema: ../../assets/docs/schemas/config.schema.json
# yaml-language-server: $schema=../../assets/docs/schemas/config.schema.json

# This file has a schema, ypu can read it to get additional definations
# Suggest use: yaml-language-server in vscode to see comments and auto-complitions

util:
    symver_ver_mapper: &symver_ver_mapper
        version_mapper:
            type: lambda
            mapper: |
                lambda ver, info: (
                    re:=__import__("re"),
                    m := re.match(r"(v)?0*(?P<major>\d+)(\.0*(?P<minor>\d+))?(\.0*(?P<patch>\d+))?(?P<pre_release>(([\w\.-]+))*)?(?P<build>(\+([\w\.]+))*)?", ver),
                    f"{m["major"]}.{m["minor"] or 0}.{m["patch"] or 0}{f"-{m["pre_release"]}" if m["pre_release"] else ""}{m["build"] or ""}"
                )[-1]
    filter_version_in_release: &release_in_filter
        release_filter:
            type: lambda
            filter: "lambda name, info: info.version in name"

handler:
    -   plugin: github_release_simple
        vendor: milkv-duo
        board_variant: 256m
        system: buildroot
        variant: v2
        repo: milkv-duo/duo-buildroot-sdk-v2
        <<: 
            - *release_in_filter
            - *symver_ver_mapper
        asset_filter:
            filter: ^milkv-duo256m-.*riscv64.*sd.*\.img.*$

    -   plugin: github_release_simple
        vendor: milkv-duo
        board_variant: 256m
        system: buildroot
        variant: v1
        repo: milkv-duo/duo-buildroot-sdk
        <<:
            - *release_in_filter
            - *symver_ver_mapper
        asset_filter:
            filter: ^milkv-duo256m-sd.*\.img.*$