name: PR checks

on:
  pull_request:
    branches:
      - main

jobs:
  dco:
    name: DCO compliance
    runs-on: ubuntu-latest
    steps:
      - name: Run dco-check
        uses: christophebedard/dco-check@0.5.0
        with:
          python-version: '3.12'
          args: '--verbose'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
